name: kindhand
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8
  flutter_feather_icons: ^2.0.0+1

  # Networking and Data
  http: ^1.4.0 # Updated
  dio: ^5.4.0

  # Storage
  shared_preferences: ^2.5.3 # Updated
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utilities
  intl: ^0.20.2
  path_provider: ^2.1.2

  # Performance
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1

  # State Management
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Build optimization
  # flutter_native_splash: ^2.3.10  # Commented out to fix build issues
  flutter_launcher_icons: ^0.14.3 # Can be updated to ^0.14.3 if needed

  # Code generation
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
